Code reorde

diff --git a/ipa-client-configure-first b/ipa-client-configure-first
--- a/ipa-client-configure-first
+++ b/ipa-client-configure-first
@@ -63,22 +63,24 @@ if [ -f /etc/ipa/ca.crt ] ; then
     cd /usr/hdp/2.6.0.3-8/zeppelin
     bin/zeppelin.sh
 else
-	#if [ "$(hostname -f)" == "$(hostname -s)" ] ; then
-		#if [ -z "$IPA_PORT_80_TCP_ADDR" ] ; then
-		#	echo "Hostname [$(hostname -f)] is not FQDN and no --link to IPA server specified." >&2
-		#	exit 2
-		#fi
-		IPA=$( curl -si http://$IPA_PORT_80_TCP_ADDR/ | perl -lne 'm!^Location:\shttps?://(.+?)/! and print $1' )
-		IPASERVERDOMAIN=${IPA#*.}
-		HOSTNAME_FQDN=$( hostname ).$IPASERVERDOMAIN
-		HOSTNAME_OPTS=--hostname=$HOSTNAME_FQDN
-		# This will always fail if the container is not run as privileged
-		if ! hostnamectl set-hostname $HOSTNAME_FQDN ; then
-			echo "Failed to set hostname to [$HOSTNAME_FQDN]" >&2
-			exit 1
+
+	IPA=$( curl -si http://$IPA_PORT_80_TCP_ADDR/ | perl -lne 'm!^Location:\shttps?://(.+?)/! and print $1' )
+	IPASERVERDOMAIN=${IPA#*.}
+	HOSTNAME_FQDN=$( hostname ).$IPASERVERDOMAIN
+	HOSTNAME_OPTS=--hostname=$HOSTNAME_FQDN
+	# This will always fail if the container is not run as privileged
+	if ! hostnamectl set-hostname $HOSTNAME_FQDN ; then
+		echo "Failed to set hostname to [$HOSTNAME_FQDN]" >&2
+		exit 1
+	fi
+	echo "Hostname set to $HOSTNAME_FQDN"
+	
+	if [ "$(hostname -f)" == "$(hostname -s)" ] ; then
+		if [ -z "$IPA_PORT_80_TCP_ADDR" ] ; then
+			echo "Hostname [$(hostname -f)] is not FQDN and no --link to IPA server specified." >&2
+			exit 2
 		fi
-		echo "Hostname set to $HOSTNAME_FQDN"
-	#fi
+	fi
 
 	/usr/sbin/ipa-client-install $IPA_CLIENT_INSTALL_OPTS --force --no-nisdomain -p admin -w "$PASSWORD" -U -v  --mkhomedir --realm=$REALM --domain=$IPASERVERDOMAIN --server=$IPASERVER  --enable-dns-updates < /dev/null
 	cp -f /etc/hostname /etc/hostname.ipa-client
